### ISSUE TITLE
Problem when the data-model is an empty array

### ISSUE THREAD

**Issue by jvrdelafuente** [boneskull/angular-tags#25] opened 2013-12-05 13:15 UTC
EXAMPLE

view->

```
<tags model="tags" src="b as b.name for b in baz "></tags>
```

controller->

```
$scope.tags=[];
$scope.baz=[{name="name1", extraData="extra1"}.{name="name2", extraData="extra2"}];
```

When I try to add some tags, with this configuration the result is:

tags-> ["name1","name2"]

The expected result would be:

tags-> [{name="name1", extraData="extra1"}.{name="name2", extraData="extra2"}]

PROBLEM

The problem is related with this section of code:

```
           // determine what format we're in
           model = scope.model;
           if (angular.isString(model)) {
             pureStrings = true;
           }
           else if (angular.isArray(model)) {
             stringArray = true;
             i = model.length;
             while (i--) {
               if (!angular.isString(model[i])) {
                 stringArray = false;
                 break;
               }
             }
           }
```

If the model is an empty array, it set stringArray to true.

MY SOLUTION (It could be better, this is a fast solution)

```
else if (angular.isArray(model)) {
             stringArray = false;
             i = model.length;
             while (i--) {
               if (angular.isString(model[i])) {
                 stringArray = true;
                 break;
               }
             }
           }
                 //Custom solution
```

**Comment by boneskull** [comment] 2014-05-16 08:50
Yeah this is a known issue.  If the array is string array by default but it was _intended_ to be an object array, and we start adding objects to it, we'll have a problem.

I'm thinking of just making this a switch and defaulting to objects.

**Comment by boneskull** [comment] 2014-05-16 08:52
dupe of #18

**Closed as completed by boneskull** 2014-05-16 08:52 UTC
Labels: duplicate
